version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-ndk
    environment:
      JVM_OPTS: -Xmx3078m
    steps:
      - checkout
      - run:
          name: Build library and app in debug configuration
          command: ./gradlew assembleDebug
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Build library and app in release configuration
          command: ./gradlew assembleDebug
